<a href="https://colab.research.google.com/github/sungjin417/sesac-phython/blob/master/%EA%B5%90)%EB%8C%80%EA%B7%9C%EB%AA%A8_LLM%EC%9D%84_%ED%99%9C%EC%9A%A9%ED%95%9C_%EC%A7%80%EC%8B%9D_%EC%B1%97%EB%B4%87_%EA%B0%9C%EB%B0%9C_3%EC%9D%BC%EC%B0%A8(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 🌼 대규모 LLM을 활용한 지식 챗봇 개발 - 3차시(24.11.25)

---

In [1]:
import numpy as np
import random
import tensorflow as tf
from transformers import AutoTokenizer
from transformers import TFGPT2LMHeadModel

In [2]:
model = TFGPT2LMHeadModel.from_pretrained('skt/kogpt2-base-v2', from_pt=True)
tokenizer = AutoTokenizer.from_pretrained('skt/kogpt2-base-v2')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/1.00k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/513M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFGPT2LMHeadModel: ['transformer.h.9.attn.masked_bias', 'transformer.h.3.attn.masked_bias', 'transformer.h.5.attn.masked_bias', 'transformer.h.11.attn.masked_bias', 'transformer.h.10.attn.masked_bias', 'transformer.h.2.attn.masked_bias', 'transformer.h.4.attn.masked_bias', 'transformer.h.1.attn.masked_bias', 'lm_head.weight', 'transformer.h.7.attn.masked_bias', 'transformer.h.0.attn.masked_bias', 'transformer.h.8.attn.masked_bias', 'transformer.h.6.attn.masked_bias']
- This IS expected if you are initializing TFGPT2LMHeadModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFGPT2LMHeadModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassifica

tokenizer.json:   0%|          | 0.00/2.83M [00:00<?, ?B/s]

In [3]:
sent = '인생에 대하여'

In [4]:
input_ids = tokenizer.encode(sent)

In [5]:
input_ids

[17831, 8022, 10332]

In [6]:
input_ids = tf.convert_to_tensor([input_ids])
# 정수 리스트를 텐서로 변환

In [7]:
input_ids.shape
# 2차원 텐서로 변환 되었음
# (1,3) : (입력데이터의 배치 크기, 문장의 토큰 수)

TensorShape([1, 3])

In [8]:
output = model.generate(input_ids, max_length = 128, repetition_penalty = 2.0, use_cache = True)
# repetition_penalty = 2.0 : 일반적으로 사용
# repetition_penalty = 1.0 : 패널티가 없음
# use_cache = True : 전에 사용했던 문장을 생성하는데 사용했던 캐시 사용

In [9]:
output_ids = output.numpy().tolist()[0]

In [10]:
print(output_ids)

[17831, 8022, 10332, 375, 8146, 8196, 9148, 12102, 19520, 13997, 11649, 50997, 9277, 8263, 17885, 11213, 8159, 9178, 10972, 9782, 9018, 18814, 9325, 9094, 13368, 11799, 25579, 9029, 6947, 41481, 17582, 12517, 9080, 10413, 9023, 9278, 9650, 9257, 22507, 11594, 28569, 45937, 18607, 9199, 9554, 24692, 9207, 14801, 21554, 10206, 15190, 45307, 10021, 9063, 9745, 23236, 9167, 10727, 9048, 7762, 8135, 45023, 46319, 9031, 10734, 12353, 7055, 13548, 9422, 38516, 12532, 21871, 11382, 9845, 9685, 9337, 9362, 15538, 9402, 25665, 7071, 11064, 23175, 7252, 13889, 9706, 9033, 12089, 13484, 18561, 16357, 17091, 7892, 15085, 12277, 24082, 43056, 9022, 27478, 9927, 10152, 36294, 9380, 23586, 11983, 23715, 7489, 11312, 8705, 9025, 21159, 11777, 16040, 26195, 11334, 20430, 10978, 23955, 47637, 15378, 10074, 9036, 9340, 23880, 10687, 12487, 9416, 14485]


In [11]:
tokenizer.decode(output_ids)

'인생에 대하여\n이제부터 나는 나의 삶을 어떻게 살아야 하는지 생각해보고자 한다.\n나는 지금 이 순간에도 내 삶의 의미를 찾고 있다.\n그것은 내가 살고 있는 삶에서 가장 중요한 것이다.\n내가 사는 삶은 나에게 주어진 것이 아니라 나를 위해 존재하는 것이기 때문이다.\n나의 삶이 바로 나 자신의 삶에 대한 가치이다.\n삶은 내게 부여된 것만이 아니다.\n나 자신을 위한 것이기도 하다.\n나를 위해서 존재해야 할 것은 오직 하나뿐이다.\n내 안에 내재된 가치를 발견하는 것, 그것이야말로 진정한 자아실현의 출발점이다.\n그리고 그 가치는 곧 자기 자신에 의해 결정된다.\n자기 자신에게만 집중할 수 있다면 그것은 결코 불가능한 일이 아닐지도 모른다.\n그러나 우리는 이미 한 가지 분명한 사실을 알고 있었다.\n바로'

In [12]:
output = model(input_ids)

In [13]:
top5 = tf.math.top_k(output.logits[0,-1], k=5)
top5

TopKV2(values=<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([10.868139, 10.436856,  9.705596,  9.644245,  9.270872],
      dtype=float32)>, indices=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([  375, 11120,   387, 17885,  9366], dtype=int32)>)

In [14]:
tokenizer.convert_ids_to_tokens(top5.indices.numpy())

['\n', '▁이야기', ',', '▁생각해', '▁많은']

In [15]:
top5_values_list = top5.values.numpy().tolist()
top5_values_list

[10.868139266967773,
 10.436856269836426,
 9.705595970153809,
 9.644245147705078,
 9.270872116088867]

In [16]:
# tokenizer.convert_ids_to_tokens(top5.values())

In [17]:
sent = '내일 아침에'
input_ids = tokenizer.encode(sent)
# 입력 문장을 정수 인덱스 리스트로 변환 후 input_ids에 저장

while len(input_ids) < 50:
  # 텍스트 총 길이(토큰개수)가 50개 미만인 동안 새로운 단어 추가
  output = model(np.array([input_ids]))
  # 현재까지 생성된 토큰(input_ids)를 모델에 입력으로 제공
  top5 = tf.math.top_k(output.logits[0, -1], k=5)
  # top5 단어들을 추출
  token_id = random.choice(top5.indices.numpy())
  # top5 단어들 중 랜덤으로 다음 단어 선택
  # 모델 출력의 다양성을 확보하기 위함
  input_ids.append(token_id)
  # input_ids에 token_id 저장
tokenizer.decode(input_ids)
# 정수 인덱스를 한글로 decoding하여 출력

'내일 아침에 발표됩니다.\n지금도 말씀드렸다\n마는 그거까지는 말씀드리지 못하지만 그래도 그거까지는 좀 생각을 했으면 합니다.\n지금 말씀을 드리기가 어렵지 않았겠습니까.\n그래가지고 그~ 뭐~ 그~ 이'